#!/usr/bin/env python3
"""Chapter 4: Materials and Methods"""

def add_materials_methods(pdf):
    pdf.add_page()
    pdf.section_title("CHAPTER 4: MATERIALS AND METHODS")
    
    pdf.heading("4.1 Study Design")
    pdf.body("This was a hospital-based, observational, descriptive, cross-sectional study designed to evaluate the prevalence and pattern of anatomical variations of paranasal air sinuses in the South Gujarat population using Computed Tomography (CT) imaging.")
    
    pdf.heading("4.2 Place of Study")
    pdf.body("The study was conducted in the Department of Anatomy in collaboration with the Department of Radiology, [Medical College Name], Surat, Gujarat. The institution serves as a tertiary care referral center for the entire South Gujarat region, drawing patients from the districts of Surat, Navsari, Valsad, Tapi, Bharuch, Narmada, and Dang.")
    
    pdf.heading("4.3 Study Period")
    pdf.body("The study was conducted over a period of 18 months, from November 2024 to April 2026. Data collection extended over 12 months, followed by 6 months for analysis, interpretation, and thesis preparation.")
    
    pdf.heading("4.4 Study Population")
    pdf.body("The study population consisted of patients who underwent CT scanning of the paranasal sinuses for various clinical indications during the study period. All eligible CT scans meeting the inclusion criteria were included in the analysis.")
    
    pdf.heading("4.5 Sample Size Calculation")
    pdf.body("Sample size was calculated using the formula for prevalence studies:")
    pdf.body("n = Z^2 x p x (1-p) / d^2")
    pdf.body("Where:")
    pdf.bullet("Z = 1.96 (for 95% confidence interval)")
    pdf.bullet("p = expected prevalence (taken as 50% for maximum sample size)")
    pdf.bullet("d = absolute precision (5%)")
    pdf.body("Calculated minimum sample size = 384")
    pdf.body("Allowing for 10% attrition rate and to ensure adequate power for subgroup analysis, the final sample size was determined as 300 patients (600 sides).")
    
    pdf.heading("4.6 Sampling Method")
    pdf.body("Consecutive sampling method was used. All patients undergoing CT paranasal sinus during the study period and meeting the inclusion criteria were included until the required sample size was achieved.")
    
    pdf.heading("4.7 Inclusion Criteria")
    pdf.numbered("1", "Patients aged 18 to 65 years")
    pdf.numbered("2", "Both male and female patients")
    pdf.numbered("3", "Residents of South Gujarat region (minimum 5 years of residence)")
    pdf.numbered("4", "Patients undergoing CT paranasal sinus for various indications:")
    pdf.bullet("Chronic rhinosinusitis evaluation")
    pdf.bullet("Headache evaluation")
    pdf.bullet("Pre-operative planning for FESS")
    pdf.bullet("Other clinical indications")
    pdf.numbered("5", "Technically adequate CT scans with good quality images in axial, coronal, and sagittal planes")
    pdf.numbered("6", "Patients/relatives willing to provide informed consent")
    
    pdf.heading("4.8 Exclusion Criteria")
    pdf.numbered("1", "Patients with previous history of sinonasal surgery")
    pdf.numbered("2", "Active sinonasal malignancy or destructive lesions")
    pdf.numbered("3", "Major facial trauma with sinus involvement")
    pdf.numbered("4", "Congenital craniofacial anomalies (cleft palate, choanal atresia, etc.)")
    pdf.numbered("5", "Sinonasal polyposis with significant anatomical distortion")
    pdf.numbered("6", "Patients below 18 years (incomplete sinus development)")
    pdf.numbered("7", "Patients above 65 years (potential age-related changes)")
    pdf.numbered("8", "Pregnant women (due to radiation concerns)")
    pdf.numbered("9", "CT scans with motion artifacts or technical inadequacies")
    pdf.numbered("10", "Patients not consenting for inclusion in study")
    
    pdf.heading("4.9 Ethical Considerations")
    pdf.body("The study protocol was approved by the Institutional Ethics Committee (IEC) of [Medical College Name] before commencement of the study (Approval reference: IEC/2024/123, dated [date]).")
    pdf.body("Key ethical considerations included:")
    pdf.bullet("Written informed consent obtained from all participants/legal guardians")
    pdf.bullet("Patient confidentiality maintained throughout the study")
    pdf.bullet("No additional radiation exposure - only existing CT scans were utilized")
    pdf.bullet("Right to withdraw from study at any time without affecting clinical care")
    pdf.bullet("Data anonymization for analysis and publication")
    pdf.bullet("Compliance with Declaration of Helsinki and ICMR ethical guidelines")
    
    pdf.heading("4.10 CT Scan Protocol")
    pdf.subheading("4.10.1 CT Scanner Specifications")
    pdf.bullet("Machine: 128-slice Multi-Detector CT scanner")
    pdf.bullet("Manufacturer: [Brand Name and Model]")
    pdf.bullet("Slice thickness: 0.625 mm")
    pdf.bullet("Reconstruction interval: 0.625 mm")
    pdf.bullet("Tube voltage: 120 kVp")
    pdf.bullet("Tube current: 200-300 mA (auto-modulation)")
    pdf.bullet("Field of view (FOV): 18-22 cm")
    pdf.bullet("Matrix: 512 x 512")
    pdf.bullet("Algorithm: Bone (sharp) and soft tissue algorithms")
    
    pdf.subheading("4.10.2 Patient Preparation and Positioning")
    pdf.bullet("Patient explained the procedure")
    pdf.bullet("Removal of metallic objects from head and neck region")
    pdf.bullet("Supine position on CT table")
    pdf.bullet("Head positioned in standard anatomical position")
    pdf.bullet("Eyes closed during scanning")
    pdf.bullet("Forehead and chin in same horizontal plane")
    pdf.bullet("Immobilization with head holder")
    
    pdf.subheading("4.10.3 Scanning Parameters")
    pdf.bullet("Scanning direction: Cranio-caudal")
    pdf.bullet("Scan range: From frontal sinus to the upper teeth")
    pdf.bullet("Scan duration: Approximately 5-7 seconds")
    pdf.bullet("Breath-hold instructions during scan")
    pdf.bullet("No intravenous contrast (unless specifically indicated)")
    
    pdf.subheading("4.10.4 Image Reconstruction")
    pdf.bullet("Axial source images")
    pdf.bullet("Coronal multiplanar reconstructions (MPR)")
    pdf.bullet("Sagittal multiplanar reconstructions (MPR)")
    pdf.bullet("Bone window settings: WW 2000, WL 400")
    pdf.bullet("Soft tissue window: WW 350, WL 40")
    pdf.bullet("3D reconstructions when needed")
    
    pdf.heading("4.11 Image Analysis")
    pdf.subheading("4.11.1 Workstation Used")
    pdf.body("Images were analyzed on a dedicated radiology workstation with multiplanar reconstruction (MPR) capabilities. DICOM (Digital Imaging and Communications in Medicine) format images were viewed using [Software Name] software.")
    
    pdf.subheading("4.11.2 Reviewers")
    pdf.body("Each CT scan was independently evaluated by two reviewers:")
    pdf.bullet("Primary reviewer: Postgraduate resident in Anatomy (the candidate)")
    pdf.bullet("Secondary reviewer: Consultant radiologist with >10 years experience in sinus imaging")
    pdf.body("In case of disagreement, the scan was re-evaluated jointly to reach consensus. A senior anatomist was consulted for difficult cases.")
    
    pdf.heading("4.12 Parameters Studied")
    pdf.body("The following parameters were systematically evaluated for each CT scan:")
    
    pdf.subheading("4.12.1 Demographic Parameters")
    pdf.bullet("Age (in years)")
    pdf.bullet("Gender (male/female)")
    pdf.bullet("Indication for CT scan")
    pdf.bullet("District of residence")
    
    pdf.subheading("4.12.2 Nasal Septum Parameters")
    pdf.bullet("Presence of deviated nasal septum (DNS)")
    pdf.bullet("Direction of deviation (right/left/S-shaped)")
    pdf.bullet("Mladina classification (Type 1-7)")
    pdf.bullet("Severity grading: Mild (<9 deg), Moderate (9-15 deg), Severe (>15 deg)")
    pdf.bullet("Presence of septal spur")
    pdf.bullet("Location of spur")
    
    pdf.subheading("4.12.3 Turbinate Parameters")
    pdf.bullet("Presence of concha bullosa (right/left/bilateral)")
    pdf.bullet("Type of concha bullosa (lamellar/bulbous/extensive)")
    pdf.bullet("Paradoxical middle turbinate")
    pdf.bullet("Secondary middle turbinate")
    pdf.bullet("Inferior turbinate hypertrophy")
    pdf.bullet("Superior turbinate variations")
    
    pdf.subheading("4.12.4 Uncinate Process Parameters")
    pdf.bullet("Superior attachment type (Stammberger I-VI)")
    pdf.bullet("Pneumatized uncinate process")
    pdf.bullet("Atelectatic uncinate process")
    pdf.bullet("Bifid uncinate process")
    
    pdf.subheading("4.12.5 Ethmoid Sinus Parameters")
    pdf.bullet("Agger nasi cells (presence, size)")
    pdf.bullet("Haller cells (presence, size, laterality)")
    pdf.bullet("Onodi cells (presence, relationship with optic nerve)")
    pdf.bullet("Frontal cells (Kuhn type I-IV)")
    pdf.bullet("Supraorbital ethmoid cells")
    pdf.bullet("Lamina papyracea integrity")
    
    pdf.subheading("4.12.6 Maxillary Sinus Parameters")
    pdf.bullet("Maxillary sinus hypoplasia (Bolger type I-III)")
    pdf.bullet("Maxillary sinus aplasia")
    pdf.bullet("Underwood septa (number, location)")
    pdf.bullet("Accessory maxillary ostium")
    pdf.bullet("Dental root protrusion into sinus")
    pdf.bullet("Sinus floor relationship with teeth")
    
    pdf.subheading("4.12.7 Frontal Sinus Parameters")
    pdf.bullet("Frontal sinus aplasia (unilateral/bilateral)")
    pdf.bullet("Frontal sinus hypoplasia")
    pdf.bullet("Frontal sinus asymmetry")
    pdf.bullet("Intersinus septum location")
    pdf.bullet("Frontal sinus septations")
    
    pdf.subheading("4.12.8 Sphenoid Sinus Parameters")
    pdf.bullet("Pneumatization type (Hamberger: conchal/presellar/sellar)")
    pdf.bullet("Septation pattern (single/multiple/asymmetric)")
    pdf.bullet("Septum attachment to ICA canal")
    pdf.bullet("Lateral recess (pterygoid recess)")
    pdf.bullet("ICA dehiscence (right/left)")
    pdf.bullet("ICA protrusion into sinus")
    pdf.bullet("Optic nerve relationship (DeLano type I-IV)")
    pdf.bullet("Optic nerve dehiscence")
    pdf.bullet("Pneumatized anterior clinoid process")
    pdf.bullet("Pneumatized pterygoid process")
    
    pdf.subheading("4.12.9 Skull Base Parameters")
    pdf.bullet("Keros classification (Type I/II/III)")
    pdf.bullet("Cribriform plate asymmetry")
    pdf.bullet("Anterior ethmoidal artery position")
    pdf.bullet("Posterior ethmoidal artery position")
    
    pdf.heading("4.13 Data Collection and Recording")
    pdf.body("A standardized proforma (Annexure IV) was used to record all parameters systematically. Data was entered into Microsoft Excel spreadsheets for analysis. Each entry was double-checked to ensure accuracy.")
    
    pdf.heading("4.14 Statistical Analysis")
    pdf.subheading("4.14.1 Software Used")
    pdf.bullet("SPSS Version 25.0 for Windows (IBM Corporation, USA)")
    pdf.bullet("Microsoft Excel 2019 for data tabulation and basic analysis")
    pdf.bullet("GraphPad Prism for graphical representations")
    
    pdf.subheading("4.14.2 Statistical Methods")
    pdf.bullet("Descriptive statistics: Mean, standard deviation, frequencies, percentages")
    pdf.bullet("Continuous variables: Mean +/- SD, range")
    pdf.bullet("Categorical variables: Numbers and percentages")
    pdf.bullet("Comparison of proportions: Chi-square test (or Fisher's exact test)")
    pdf.bullet("Comparison of means: Student's t-test (independent samples)")
    pdf.bullet("Multiple comparisons: ANOVA where applicable")
    pdf.bullet("Correlation analysis: Pearson's correlation coefficient")
    pdf.bullet("p-value < 0.05 considered statistically significant")
    pdf.bullet("95% confidence intervals reported where applicable")
    
    pdf.heading("4.15 Quality Control Measures")
    pdf.bullet("Pilot study with 30 cases to refine the protocol")
    pdf.bullet("Inter-observer agreement assessed using kappa statistics")
    pdf.bullet("Periodic review of difficult cases by senior consultants")
    pdf.bullet("Standardized terminology and definitions used")
    pdf.bullet("Calibration of measurement tools on workstation")
    
    pdf.heading("4.16 Limitations of Methodology")
    pdf.bullet("Hospital-based study may not represent general population")
    pdf.bullet("Selection bias due to clinical indication")
    pdf.bullet("Cross-sectional design limits causal inferences")
    pdf.bullet("Retrospective evaluation of CT scans")
    pdf.bullet("Limited age range (18-65 years)")
