#!/usr/bin/env python3
"""Additional comprehensive content to reach 220 pages"""

def add_detailed_anatomy_review(pdf):
    """Detailed anatomy chapter expansion"""
    pdf.add_page()
    pdf.heading("3.11 Detailed Surgical Anatomy of Each Sinus")
    
    pdf.subheading("3.11.1 Maxillary Sinus - Surgical Perspective")
    pdf.body("The maxillary sinus is the most commonly operated paranasal sinus due to its high incidence of infection. Understanding its detailed surgical anatomy is paramount for safe and effective surgery.")
    
    pdf.body("Surgical Landmarks:")
    pdf.bullet("Maxillary line: a curvilinear ridge representing the projection of nasolacrimal duct on the lateral nasal wall")
    pdf.bullet("Uncinate process: thin sickle-shaped bone, key landmark for endoscopic surgery")
    pdf.bullet("Hiatus semilunaris: crescent-shaped opening between uncinate and ethmoid bulla")
    pdf.bullet("Maxillary sinus ostium: located in the upper part of medial wall, drains via infundibulum")
    pdf.bullet("Inferior turbinate attachment: divides anterior and posterior fontanelles")
    pdf.bullet("Posterior fontanelle: thin membranous area where accessory ostia commonly form")
    
    pdf.body("Vascular Anatomy:")
    pdf.bullet("Posterior superior alveolar artery: enters posterior wall, supplies sinus mucosa")
    pdf.bullet("Infraorbital artery: enters via infraorbital foramen, runs in superior wall")
    pdf.bullet("Greater palatine artery: enters via floor")
    pdf.bullet("Sphenopalatine artery: branches enter medial wall")
    pdf.bullet("Anterior superior alveolar artery: anterior wall blood supply")
    
    pdf.body("Neural Anatomy:")
    pdf.bullet("Maxillary nerve (V2): main innervation")
    pdf.bullet("Anterior superior alveolar nerve: anterior wall and incisor teeth")
    pdf.bullet("Middle superior alveolar nerve: variable, premolar teeth")
    pdf.bullet("Posterior superior alveolar nerve: molar teeth and posterior gingiva")
    pdf.bullet("Infraorbital nerve: roof and anterior wall")
    pdf.bullet("Greater palatine nerve: floor and medial wall")
    
    pdf.body("Lymphatic Drainage:")
    pdf.bullet("Submandibular nodes")
    pdf.bullet("Deep cervical nodes")
    pdf.bullet("Retropharyngeal nodes")
    
    pdf.body("Mucociliary Clearance:")
    pdf.body("Despite its dependent position, the maxillary sinus has well-organized mucociliary clearance. Cilia beat in a coordinated pattern (10-15 Hz) directing mucus toward the natural ostium. This explains why creating a large antrostomy without addressing the natural ostium can fail - cilia continue to beat toward the natural ostium causing mucus recirculation.")
    
    pdf.subheading("3.11.2 Ethmoid Labyrinth - Surgical Anatomy")
    pdf.body("The ethmoid labyrinth is the most complex and clinically important region in sinus surgery. Its detailed anatomy must be thoroughly understood.")
    
    pdf.body("Ethmoid Bone Components:")
    pdf.bullet("Cribriform plate: roof of nasal cavity, perforated for olfactory nerves")
    pdf.bullet("Crista galli: midline bony projection")
    pdf.bullet("Perpendicular plate: forms upper part of nasal septum")
    pdf.bullet("Labyrinth (lateral mass): contains air cells")
    pdf.bullet("Superior turbinate: upper part of ethmoid")
    pdf.bullet("Middle turbinate: clinically most important")
    
    pdf.body("Lamellae of Ethmoid:")
    pdf.body("The ethmoid has classical lamellae (sheets of bone) that serve as surgical landmarks:")
    pdf.bullet("First lamella: Uncinate process")
    pdf.bullet("Second lamella: Anterior face of ethmoid bulla")
    pdf.bullet("Third lamella: Basal lamella of middle turbinate (separates anterior from posterior ethmoid)")
    pdf.bullet("Fourth lamella: Anterior face of superior turbinate")
    
    pdf.body("Spaces Between Lamellae:")
    pdf.bullet("Frontal recess: between agger nasi and middle turbinate")
    pdf.bullet("Suprabullar recess: above ethmoid bulla")
    pdf.bullet("Retrobullar recess: behind ethmoid bulla")
    pdf.bullet("Sphenoethmoidal recess: between superior turbinate and sphenoid")
    
    pdf.body("Critical Surgical Landmarks:")
    pdf.bullet("Maxillary line: indicates projection of frontal recess")
    pdf.bullet("Anterior ethmoidal artery: marks transition from anterior to posterior ethmoid")
    pdf.bullet("Posterior ethmoidal artery: marks border with sphenoid")
    pdf.bullet("Lamina papyracea: lateral border with orbit")
    pdf.bullet("Fovea ethmoidalis and cribriform plate: superior border")
    
    pdf.subheading("3.11.3 Frontal Sinus - Drainage Anatomy")
    pdf.body("The frontal sinus drainage anatomy is the most complex and has received considerable attention in literature.")
    
    pdf.body("Frontal Recess Anatomy:")
    pdf.body("The frontal recess (formerly nasofrontal duct) is the drainage pathway from frontal sinus to middle meatus. It is hourglass-shaped with:")
    pdf.bullet("Frontal infundibulum (above ostium)")
    pdf.bullet("Frontal ostium (narrowest point)")
    pdf.bullet("Frontal recess proper (below ostium, opens into middle meatus)")
    
    pdf.body("Boundaries of Frontal Recess:")
    pdf.bullet("Anterior: Agger nasi cell")
    pdf.bullet("Posterior: Anterior wall of ethmoid bulla / suprabullar cells")
    pdf.bullet("Medial: Middle turbinate")
    pdf.bullet("Lateral: Lamina papyracea")
    pdf.bullet("Superior: Frontal sinus floor")
    pdf.bullet("Inferior: Middle meatus")
    
    pdf.body("Wormald's Building Block Concept:")
    pdf.body("Wormald (2003) introduced a building block approach to understand frontal recess anatomy:")
    pdf.numbered("1", "Identify agger nasi cell (always anterior)")
    pdf.numbered("2", "Identify ethmoid bulla (posterior border)")
    pdf.numbered("3", "Identify any frontoethmoid cells (Type I-IV)")
    pdf.numbered("4", "The frontal sinus drains between these structures")
    
    pdf.body("Kuhn Classification of Frontal Cells:")
    pdf.body("Bent and Kuhn (1994) classified frontal recess cells:")
    pdf.bullet("Type I: Single cell above agger nasi, below frontal sinus floor (33%)")
    pdf.bullet("Type II: Tier of cells above agger nasi (9.5%)")
    pdf.bullet("Type III: Single cell extending from agger nasi into frontal sinus (9.5%)")
    pdf.bullet("Type IV: Isolated cell within frontal sinus (1%)")
    
    pdf.subheading("3.11.4 Sphenoid Sinus - Skull Base Relations")
    pdf.body("The sphenoid sinus has the most complex anatomical relationships of all paranasal sinuses, with critical neurovascular structures in close proximity.")
    
    pdf.body("Anatomical Relations:")
    pdf.bullet("Anteriorly: Sphenoethmoidal recess, posterior nasal septum")
    pdf.bullet("Posteriorly: Clivus, brainstem, basilar artery, posterior cranial fossa")
    pdf.bullet("Superiorly: Pituitary gland, optic chiasm, anterior cranial fossa")
    pdf.bullet("Inferiorly: Vidian canal, palatine bone, nasopharynx")
    pdf.bullet("Laterally: Cavernous sinus contents (ICA, CN III, IV, V1, V2, VI)")
    
    pdf.body("Critical Structures in Lateral Wall:")
    pdf.bullet("Internal carotid artery (cavernous segment)")
    pdf.bullet("Optic nerve (canalicular and intracranial)")
    pdf.bullet("Maxillary nerve (V2) in foramen rotundum")
    pdf.bullet("Vidian nerve in vidian canal")
    pdf.bullet("Abducens nerve (CN VI)")
    
    pdf.body("Sphenoid Sinus Septations:")
    pdf.body("The sphenoid sinus is divided by intersinus septa that are highly variable. Critical clinical aspects:")
    pdf.bullet("Single midline septum: 32-44%")
    pdf.bullet("Single deviated septum: 30-50%")
    pdf.bullet("Multiple septa: 18-32%")
    pdf.bullet("Septum attaching to ICA canal: 8-25% (CRITICAL - removal can injure ICA)")
    
    pdf.body("Onodi Cell Special Considerations:")
    pdf.bullet("Located posterosuperolateral to sphenoid")
    pdf.bullet("Optic nerve runs through or adjacent to lateral wall")
    pdf.bullet("Often mistaken for sphenoid sinus on CT")
    pdf.bullet("Approach to sphenoid through Onodi increases risk")
    pdf.bullet("Pre-operative identification critical")

def add_advanced_techniques(pdf):
    """Advanced surgical techniques chapter"""
    pdf.add_page()
    pdf.heading("3.12 Advanced Surgical Techniques and Considerations")
    
    pdf.subheading("3.12.1 Basic FESS Technique")
    pdf.body("The standard FESS technique involves a systematic, step-by-step approach:")
    
    pdf.body("Step 1: Endoscopic Examination")
    pdf.bullet("Visualize nasal cavity, septum, turbinates")
    pdf.bullet("Identify anatomical variations")
    pdf.bullet("Assess disease extent")
    
    pdf.body("Step 2: Uncinectomy")
    pdf.bullet("Identify uncinate process")
    pdf.bullet("Make incision along its anterior edge")
    pdf.bullet("Remove uncinate to expose ethmoid infundibulum")
    pdf.bullet("Identify maxillary sinus ostium")
    
    pdf.body("Step 3: Maxillary Antrostomy")
    pdf.bullet("Enlarge natural ostium")
    pdf.bullet("Connect with accessory ostium if present")
    pdf.bullet("Avoid creating separate openings (mucus recirculation)")
    pdf.bullet("Preserve mucosa")
    
    pdf.body("Step 4: Anterior Ethmoidectomy")
    pdf.bullet("Open ethmoid bulla")
    pdf.bullet("Remove anterior ethmoid cells systematically")
    pdf.bullet("Identify lamina papyracea (lateral)")
    pdf.bullet("Identify ethmoid roof (superior)")
    
    pdf.body("Step 5: Posterior Ethmoidectomy")
    pdf.bullet("Penetrate basal lamella of middle turbinate")
    pdf.bullet("Remove posterior ethmoid cells")
    pdf.bullet("Identify sphenoid sinus")
    pdf.bullet("Beware of Onodi cells")
    
    pdf.body("Step 6: Sphenoidotomy")
    pdf.bullet("Identify natural ostium of sphenoid")
    pdf.bullet("Located medial to superior turbinate")
    pdf.bullet("Enlarge ostium inferiorly and medially")
    pdf.bullet("Avoid lateral wall (ICA, optic nerve)")
    
    pdf.body("Step 7: Frontal Recess Surgery (if needed)")
    pdf.bullet("Most challenging part of FESS")
    pdf.bullet("Identify agger nasi cell")
    pdf.bullet("Remove frontal cells (Kuhn types)")
    pdf.bullet("Preserve mucosa around frontal ostium")
    pdf.bullet("Do not strip mucosa circumferentially")
    
    pdf.subheading("3.12.2 Modified Endoscopic Lothrop Procedure")
    pdf.body("The Draf III procedure or Modified Endoscopic Lothrop (MEL) is used for severe frontal sinus disease. It involves:")
    pdf.bullet("Wide bilateral frontal sinusotomy")
    pdf.bullet("Removal of intersinus septum")
    pdf.bullet("Removal of frontal beak")
    pdf.bullet("Creates a single common cavity")
    pdf.bullet("Indications: failed previous surgery, neoplasms, severe disease")
    
    pdf.subheading("3.12.3 Endoscopic Skull Base Surgery")
    pdf.body("Endoscopic approaches to skull base have expanded significantly:")
    pdf.bullet("Transsphenoidal approach to pituitary")
    pdf.bullet("Transethmoidal approach to anterior skull base")
    pdf.bullet("Transcribriform approach to anterior cranial fossa")
    pdf.bullet("Transpterygoid approach to middle cranial fossa")
    pdf.bullet("Transclival approach to posterior cranial fossa")
    
    pdf.body("Key requirements:")
    pdf.bullet("Detailed anatomical knowledge")
    pdf.bullet("Image-guided navigation")
    pdf.bullet("Multidisciplinary team (ENT + Neurosurgery)")
    pdf.bullet("Specialized instrumentation")
    pdf.bullet("Skull base reconstruction expertise")
    
    pdf.subheading("3.12.4 Computer-Assisted Surgical Navigation")
    pdf.body("Image-guided surgery (IGS) has revolutionized complex sinus and skull base surgery:")
    
    pdf.body("Advantages:")
    pdf.bullet("Real-time anatomical localization")
    pdf.bullet("Improved orientation in distorted anatomy")
    pdf.bullet("Increased confidence in identifying landmarks")
    pdf.bullet("Reduced surgical complications")
    pdf.bullet("Useful for revision surgery")
    pdf.bullet("Helpful for trainees")
    
    pdf.body("Limitations:")
    pdf.bullet("Cost of equipment")
    pdf.bullet("Setup time")
    pdf.bullet("Dependence on pre-operative imaging")
    pdf.bullet("Brain shift in skull base surgery")
    pdf.bullet("Not a replacement for anatomical knowledge")
    
    pdf.body("AAO-HNS Indications for IGS:")
    pdf.bullet("Revision sinus surgery")
    pdf.bullet("Distorted anatomy")
    pdf.bullet("Disease abutting skull base, orbit, optic nerve, carotid artery")
    pdf.bullet("Disease in frontal, posterior ethmoid, sphenoid sinuses")
    pdf.bullet("CSF leak repair")
    pdf.bullet("Sinonasal neoplasms")
    
    pdf.subheading("3.12.5 Powered Instrumentation (Microdebrider)")
    pdf.body("Microdebriders have transformed sinus surgery:")
    pdf.bullet("Continuous suction-cutting action")
    pdf.bullet("Precise tissue removal")
    pdf.bullet("Less mucosal trauma")
    pdf.bullet("Improved hemostasis")
    pdf.bullet("Better visualization")
    pdf.bullet("Faster surgery")
    
    pdf.body("Risks:")
    pdf.bullet("Aggressive removal in wrong area can be catastrophic")
    pdf.bullet("Orbital injury if blade enters orbit")
    pdf.bullet("Skull base injury")
    pdf.bullet("ICA injury (rare but reported)")
    pdf.bullet("Need for proper training and technique")
    
    pdf.subheading("3.12.6 Balloon Sinus Dilation")
    pdf.body("Balloon sinuplasty is a minimally invasive alternative to traditional FESS:")
    pdf.bullet("Catheter-based dilation of sinus ostia")
    pdf.bullet("Performed in office or operating room")
    pdf.bullet("Less mucosal trauma")
    pdf.bullet("Faster recovery")
    pdf.bullet("Limited applicability (not for all disease patterns)")
    pdf.bullet("Cost considerations")
    
    pdf.body("Indications:")
    pdf.bullet("Recurrent acute sinusitis")
    pdf.bullet("Mild chronic sinusitis")
    pdf.bullet("Limited disease without polyps")
    pdf.bullet("Patient preference")
    pdf.bullet("High-risk patients for general anesthesia")

def add_pathology_chapter(pdf):
    """Pathology and diseases chapter"""
    pdf.add_page()
    pdf.heading("3.13 Pathology of Paranasal Sinuses")
    
    pdf.subheading("3.13.1 Acute Rhinosinusitis (ARS)")
    pdf.body("Acute rhinosinusitis is defined as inflammation of the nose and paranasal sinuses lasting less than 12 weeks. It is one of the most common conditions in clinical practice.")
    
    pdf.body("Etiology:")
    pdf.bullet("Viral (most common): Rhinovirus, Influenza, RSV")
    pdf.bullet("Bacterial: S. pneumoniae, H. influenzae, M. catarrhalis")
    pdf.bullet("Allergic")
    pdf.bullet("Anatomical predisposition")
    
    pdf.body("Clinical Features:")
    pdf.bullet("Nasal congestion/obstruction")
    pdf.bullet("Purulent nasal discharge")
    pdf.bullet("Facial pain/pressure")
    pdf.bullet("Reduced sense of smell")
    pdf.bullet("Fever (in bacterial)")
    pdf.bullet("Headache")
    pdf.bullet("Cough")
    
    pdf.subheading("3.13.2 Chronic Rhinosinusitis (CRS)")
    pdf.body("CRS is a complex inflammatory condition of nose and paranasal sinuses lasting more than 12 weeks. EPOS 2020 classification:")
    pdf.bullet("CRS without nasal polyps (CRSsNP)")
    pdf.bullet("CRS with nasal polyps (CRSwNP)")
    pdf.bullet("Allergic fungal rhinosinusitis (AFRS)")
    pdf.bullet("Eosinophilic chronic rhinosinusitis")
    
    pdf.body("Pathophysiology:")
    pdf.bullet("Mucociliary dysfunction")
    pdf.bullet("Inflammatory cascade")
    pdf.bullet("Bacterial biofilms")
    pdf.bullet("Anatomical predisposition")
    pdf.bullet("Immune dysregulation")
    pdf.bullet("Genetic factors")
    
    pdf.body("Diagnostic Criteria (EPOS 2020):")
    pdf.numbered("1", "Two or more symptoms (one being nasal blockage or nasal discharge):")
    pdf.bullet("Nasal blockage/obstruction/congestion")
    pdf.bullet("Nasal discharge (anterior/posterior)")
    pdf.bullet("Facial pain/pressure")
    pdf.bullet("Reduction or loss of smell")
    pdf.numbered("2", "Plus either:")
    pdf.bullet("Endoscopic signs (polyps, mucopurulent discharge, edema)")
    pdf.bullet("CT changes (mucosal changes within OMC and/or sinuses)")
    pdf.numbered("3", "Duration: 12 weeks or longer")
    
    pdf.subheading("3.13.3 Nasal Polyps")
    pdf.body("Nasal polyps are non-neoplastic outgrowths of edematous nasal mucosa. They are most commonly seen in CRSwNP.")
    
    pdf.body("Pathogenesis:")
    pdf.bullet("Type 2 inflammation predominant")
    pdf.bullet("Eosinophilic infiltration")
    pdf.bullet("Edema and mucin pooling")
    pdf.bullet("Stromal fibrosis")
    
    pdf.body("Associations:")
    pdf.bullet("Asthma (Samter's triad)")
    pdf.bullet("Aspirin sensitivity")
    pdf.bullet("Cystic fibrosis")
    pdf.bullet("Allergic fungal sinusitis")
    
    pdf.body("Imaging:")
    pdf.bullet("Bilateral, multiple polyps")
    pdf.bullet("Diffuse opacification")
    pdf.bullet("Bone remodeling possible")
    pdf.bullet("Need to rule out malignancy")
    
    pdf.subheading("3.13.4 Mucoceles")
    pdf.body("Mucoceles are expansile, mucus-containing cysts that develop when sinus drainage is obstructed. They can cause local bone erosion and adjacent structure displacement.")
    
    pdf.body("Most common locations:")
    pdf.bullet("Frontal sinus (60-65%)")
    pdf.bullet("Ethmoid sinus (25-30%)")
    pdf.bullet("Maxillary sinus (5-10%)")
    pdf.bullet("Sphenoid sinus (1-5%)")
    
    pdf.body("Clinical Presentation:")
    pdf.bullet("Painless gradual swelling")
    pdf.bullet("Proptosis (frontal/ethmoid)")
    pdf.bullet("Diplopia")
    pdf.bullet("Headache")
    pdf.bullet("Visual disturbances (sphenoid)")
    
    pdf.subheading("3.13.5 Fungal Rhinosinusitis")
    pdf.body("Fungal infections of paranasal sinuses range from non-invasive to acute invasive forms:")
    
    pdf.body("Classification:")
    pdf.bullet("Allergic fungal rhinosinusitis (AFRS)")
    pdf.bullet("Fungal ball (mycetoma)")
    pdf.bullet("Acute invasive fungal rhinosinusitis (life-threatening)")
    pdf.bullet("Chronic invasive fungal rhinosinusitis")
    pdf.bullet("Granulomatous invasive fungal rhinosinusitis")
    
    pdf.body("Common pathogens:")
    pdf.bullet("Aspergillus species (most common)")
    pdf.bullet("Mucor (in immunocompromised)")
    pdf.bullet("Bipolaris")
    pdf.bullet("Curvularia")
    pdf.bullet("Alternaria")
    
    pdf.subheading("3.13.6 Sinonasal Tumors")
    pdf.body("Sinonasal neoplasms are relatively rare but can be life-threatening:")
    
    pdf.body("Benign tumors:")
    pdf.bullet("Inverted papilloma (most common)")
    pdf.bullet("Osteoma")
    pdf.bullet("Fibrous dysplasia")
    pdf.bullet("Hemangioma")
    pdf.bullet("Schwannoma")
    
    pdf.body("Malignant tumors:")
    pdf.bullet("Squamous cell carcinoma (most common)")
    pdf.bullet("Adenoid cystic carcinoma")
    pdf.bullet("Adenocarcinoma")
    pdf.bullet("Esthesioneuroblastoma (olfactory neuroblastoma)")
    pdf.bullet("Sinonasal undifferentiated carcinoma (SNUC)")
    pdf.bullet("Mucosal melanoma")
    pdf.bullet("Lymphoma")
    pdf.bullet("Sarcomas")

def add_more_discussion(pdf):
    """More discussion content"""
    pdf.add_page()
    pdf.heading("6.17 Population-based Anatomical Differences")
    
    pdf.body("The variations in prevalence rates of paranasal sinus anatomy across different populations is a well-documented phenomenon. Several studies have explored these differences:")
    
    pdf.subheading("6.17.1 Asian vs Western Populations")
    pdf.body("Several anatomical features show consistent differences:")
    pdf.bullet("Onodi cells: Higher in East Asian (Korean, Japanese) than Western populations")
    pdf.bullet("Sphenoid sinus pneumatization: Sellar type more common in Western")
    pdf.bullet("Frontal sinus size: Generally larger in Western populations")
    pdf.bullet("DNS prevalence: Variable, but some studies show higher in South Asian")
    pdf.bullet("Concha bullosa: Generally higher in Western studies")
    
    pdf.body("Possible explanations:")
    pdf.bullet("Genetic differences in craniofacial development")
    pdf.bullet("Environmental factors")
    pdf.bullet("Skull morphology variations")
    pdf.bullet("Methodological differences in studies")
    pdf.bullet("Sample size and selection bias")
    
    pdf.subheading("6.17.2 Within-Indian Variations")
    pdf.body("Even within India, regional variations exist:")
    pdf.bullet("North vs South: DNS more common in North; Onodi cells variable")
    pdf.bullet("East vs West: Limited comparative data available")
    pdf.bullet("Urban vs Rural: Few studies compare these")
    pdf.bullet("Genetic factors related to migration patterns")
    pdf.bullet("Environmental exposures (urban pollution, rural agriculture)")
    
    pdf.body("Our South Gujarat study findings support the existence of regional variations and emphasize the need for population-specific data.")
    
    pdf.subheading("6.17.3 Genetic Basis of Variations")
    pdf.body("While genetic basis of paranasal sinus variations is not fully understood, several observations suggest a hereditary component:")
    pdf.bullet("Bilateral symmetry in many variations")
    pdf.bullet("Familial occurrence reported")
    pdf.bullet("Twin studies showing concordance")
    pdf.bullet("Ethnic clustering of variations")
    pdf.bullet("Association with craniofacial syndromes")
    
    pdf.body("Future genetic studies may help identify:")
    pdf.bullet("Genes controlling sinus development")
    pdf.bullet("Risk factors for chronic sinusitis")
    pdf.bullet("Predictive markers for surgical complications")
    pdf.bullet("Personalized surgical approaches")
    
    pdf.subheading("6.17.4 Environmental Influences")
    pdf.body("Environmental factors may influence sinus development and variations:")
    pdf.bullet("Air quality and pollutants")
    pdf.bullet("Allergens and chronic inflammation")
    pdf.bullet("Climate (humidity, temperature)")
    pdf.bullet("Altitude (lower at higher altitudes)")
    pdf.bullet("Dietary factors")
    pdf.bullet("Smoking and second-hand smoke exposure")
    
    pdf.heading("6.18 Surgical Outcomes and Anatomical Variations")
    
    pdf.body("The relationship between pre-operative anatomical variations and surgical outcomes has been investigated in several studies. Key findings include:")
    
    pdf.subheading("6.18.1 Variations Affecting Surgical Difficulty")
    pdf.body("Certain variations make FESS more challenging:")
    pdf.bullet("Severe DNS - limited access")
    pdf.bullet("Multiple frontal cells - frontal recess complexity")
    pdf.bullet("Hypoplastic maxillary sinus - distorted landmarks")
    pdf.bullet("Conchal sphenoid - difficult sphenoidotomy")
    pdf.bullet("Onodi cells - altered approach")
    pdf.bullet("Atelectatic uncinate - difficult identification")
    
    pdf.subheading("6.18.2 Variations Affecting Surgical Risk")
    pdf.body("High-risk variations include:")
    pdf.bullet("Keros Type III - CSF leak risk")
    pdf.bullet("ICA dehiscence - hemorrhage risk")
    pdf.bullet("Optic nerve protrusion - blindness risk")
    pdf.bullet("Onodi cells - optic nerve injury")
    pdf.bullet("Lamina papyracea dehiscence - orbital injury")
    pdf.bullet("Cribriform plate asymmetry - skull base injury")
    
    pdf.subheading("6.18.3 Pre-operative Risk Stratification")
    pdf.body("A systematic approach to risk stratification is recommended:")
    pdf.numbered("1", "Identify all anatomical variations on pre-operative CT")
    pdf.numbered("2", "Categorize as low/moderate/high risk")
    pdf.numbered("3", "Plan surgical approach accordingly")
    pdf.numbered("4", "Decide on need for image guidance")
    pdf.numbered("5", "Have surgical team appropriately prepared")
    pdf.numbered("6", "Counsel patient on risks")
    pdf.numbered("7", "Have backup plans for complications")
    pdf.numbered("8", "Document all findings systematically")
    
    pdf.heading("6.19 Future Perspectives")
    
    pdf.body("Several emerging trends and research directions are shaping the future of paranasal sinus anatomy and surgery:")
    
    pdf.subheading("6.19.1 Artificial Intelligence Applications")
    pdf.bullet("Automated detection of anatomical variations on CT")
    pdf.bullet("Computer-aided diagnosis of sinus pathology")
    pdf.bullet("AI-assisted surgical planning")
    pdf.bullet("Predictive modeling for surgical outcomes")
    pdf.bullet("Real-time intraoperative guidance")
    
    pdf.subheading("6.19.2 Advanced Imaging Techniques")
    pdf.bullet("Ultra-high resolution CT")
    pdf.bullet("Functional CT (perfusion, dual-energy)")
    pdf.bullet("MRI advances for sinus imaging")
    pdf.bullet("3D printing for surgical planning")
    pdf.bullet("Virtual and augmented reality")
    
    pdf.subheading("6.19.3 Robotic and Minimally Invasive Surgery")
    pdf.bullet("Robotic FESS systems in development")
    pdf.bullet("Microsurgical robotic platforms")
    pdf.bullet("Single-incision techniques")
    pdf.bullet("Office-based procedures")
    pdf.bullet("Drug-eluting implants")
    
    pdf.subheading("6.19.4 Regenerative Medicine")
    pdf.bullet("Mucosal regeneration techniques")
    pdf.bullet("Tissue-engineered scaffolds")
    pdf.bullet("Stem cell therapy")
    pdf.bullet("Targeted biological therapies")
    pdf.bullet("Personalized medicine approaches")
    
    pdf.subheading("6.19.5 Translational Research")
    pdf.bullet("Anatomical variations and disease mechanisms")
    pdf.bullet("Genetic studies of sinus development")
    pdf.bullet("Molecular markers for disease")
    pdf.bullet("Outcome prediction models")
    pdf.bullet("Cost-effectiveness analyses")
